r.crypto.db.postgres.url=jdbc:postgresql://postgres/crypto
r.crypto.db.postgres.user=crypto_dev
r.crypto.db.postgres.password=crypto_dev_passw0rd

r.crypto.db.mssql.url=jdbc:sqlserver://mssql:1433;databaseName=crypto
r.crypto.db.mssql.user=sa
r.crypto.db.mssql.password=sql_server_passworD1

r.crypto.db.oracle.url=jdbc:oracle:thin:@oracle:1521:ORCLCDB
r.crypto.db.oracle.user=sys as sysdba
r.crypto.db.oracle.password=Oradoc_db1

rnet.encryption.defaultMode=DUAL_WRITE
rnet.encryption.virtualKey.nameKey=kmsNameKey
rnet.encryption.virtualKey.emailKey=kmsEmailKey
rnet.encryption.virtualKey.jsonKey=kmsJsonKey
rnet.encryption.virtualKey.contentKey=kmsContentKey
rnet.encryption.virtualKey.keystoreKey=encryption_key
rnet.encryption.localKms.testTenants=tenant1,tenant2,tenant3,disabledTenant,migrationProcessorTestTenant
rnet.encryption.mode.disabledTenant=DISABLED

rnet.vault.base.path=/transit/rxrapid/dev/usw2/tenants/

showSQL=true
vaultEnabled=false
rnet.encryption.vault.exportKeys=false
rnet.encryption.cacheRemoteEncryptionProvider=false
rnet.encryption.entityEncryptionService.batchEncryption.enabled=false
rnet.encryption.job.id=hi
